version: '3'
services:
    pwn:
        container_name: pwn
        image: j0k3r10101/pwn
        cap_add:
            - SYS_PTRACE
        ports:
            - "23946:23946"
        volumes:
            - /home/kali/htb/:/ctf/work/htb/
