version: '3'
services:
    pwn:
        container_name: pwn_test
        image: skysider/pwndocker
        cap_add:
            - SYS_PTRACE
        ports:
            - "23946:23946"
        volumes:
            - /home/kali/htb/:/ctf/work/htb/
